sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t klaidigorishti/app.docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true klaidigorishti/app.docker-react npm run test -- --coverage
